version: "3"

services:
  postgres:
    image: "postgres:10.4-alpine"
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    depends_on:
      - "postgres"
    build: .
    command: sh start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitexchange
      - gems:/gems
 

volumes:
  postgres:
  gems: